#!/bin/sh

set -eux

CRYPTDEVICE_ID="cryptdevice=$(blkid | awk '$4=="PARTLABEL=\"lvm\""{print $2}'| sed -e's/\"//g'):lvm"
ROOT_ID="root=$(blkid | awk '$1 == "/dev/mapper/brain-root:"{print $2}' | sed -e's/\"//g')"

if [ -z "$CRYPTDEVICE_ID" ]; then
    echo "could not find CRYPTDEVICE_ID"
    exit 1
fi

if [ -z "$ROOT_ID" ]; then
    echo "could not find ROOT_ID"
    exit 1
fi

bootctl --path=/mnt/boot install

echo -e "default arch\ntimeout 2\neditor 0" > /mnt/boot/loader/loader.conf
echo -e "title Arch Linux\nlinux /vmlinuz-linux\ninitrd /initramfs-linux.img\noptions $CRYPTDEVICE_ID $ROOT_ID quiet rw" > /mnt/boot/loader/entries/arch.conf
