#!/bin/sh
set -eux
./create-filesystem "${INSTALL_DISK}" "${ROOT_SIZE}" "${SWAP_SIZE}"
./install-packages
./configure-system "${HOSTNAME}"
./configure-post-install
./configure-bootloader "${BOOT_PARTITION}"
./setup-user "${USER_NAME}" "${USER_SHELL}"
