#!/bin/sh

if ! ping -c 1 -q www.google.com >/dev/null 2>&1; then
    echo "no internet connection"
    exit 1
fi

set -eux
./create-filesystem "${INSTALL_DISK}" "${ROOT_SIZE}" "${SWAP_SIZE}"
./install-packages
./configure-system "${HOSTNAME}"
./configure-post-install
./configure-bootloader
./setup-user "${USER_NAME}" "${USER_SHELL}"
